### ISSUE TITLE
bluekvirus shows up as commit author from commits done within the VM

### ISSUE THREAD

**Issue by admosity** [phusion/open-vagrant-boxes#22]
We used this box: [https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box](https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box) and installed git onto the machine, just a regular `sudo apt-get install git`. For whatever reason, when a developer does a commit for our private project from within the VM, it comes up as the following user: @bluekvirus. Is there a reason for this? Should I be concerned about something?

Thanks!

**Comment by FooBarWidget** [comment]
If that happens, then it's likely because there's a file /home/vagrant/.gitconfig inside the VM which references bluekvirus as the author. However I grepped the entire VM filesystem and could not find any file which contains that string. Could you check your VM? What does your gitconfig say? Can you run this inside the VM and tell me what you see?

    sudo grep bluekvirus /{usr,bin,sbin,lib*,root,etc,var,home,opt} -nr

**Comment by admosity** [comment]
I will tell my devs to run this.

**Comment by admosity** [comment]
Also, when they run `git config --list` it doesn't list out any usernames/emails.

**Comment by admosity** [comment]
```
vagrant@ubuntu-14:/vagrant$ sudo grep bluekvirus /{usr,bin,sbin,lib*,root,etc,var,home,opt} -nr
/var/log/auth.log:220:Apr  3 14:53:01 ubuntu-14 sudo:  vagrant : TTY=pts/0 ; PWD=/vagrant ; USER=root ; COMMAND=/bin/grep bluekvirus /usr /bin /sbin /lib /lib64 /root /etc /var /home /opt -nr
```

This is the output from their machines, so basically nothing...

**Comment by FooBarWidget** [comment]
And the problem still occurs? If you run a 'git commit' inside the VM, the commit still shows up with bluekvirus as the owner?

Which account were you running git as while in the VM? Was it 'vagrant'?

**Comment by admosity** [comment]
I figured out the issue. So by default git takes the username of the current user and the hostname and makes that the email for the commit (if the username and email wasn't set), so that is: `vagrant@ubuntu-14.04-amd64-vbox`. 

I changed my author email outside of the box and made a commit as that author email and pushed that up. Someone on github registered `vagrant@ubuntu-14.04-amd64-vbox` as their email address. Github pulls that address and renders that user.

**Comment by admosity** [comment]
![image](https://cloud.githubusercontent.com/assets/4655972/7050120/18f2ff66-dded-11e4-926b-d5165fbfab89.png)

For reference, here's the commit from my local (not the vm) with just the email address changed to `vagrant@ubuntu-14.04-amd64-vbox`. 

Here's a commit from within the vagrant box:

![image](https://cloud.githubusercontent.com/assets/4655972/7050153/43499374-dded-11e4-865c-dba55d3cb2c2.png)

**Comment by FooBarWidget** [comment]
Glad the issue is sorted out.
